version: "3"

services:
  web:
    platform: linux/x86_64
    image: php:7.4-apache
    volumes:
      - ./:/var/www/html
      - ./docker/apache2/sites-available:/etc/apache2/sites-available
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8080:80
